[package]
name = "konnoohmachi"
version = "0.1.4"
authors = ["Marius Kriegerowski <marius.kriegerowski@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "konnoohmachi"

# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.15.0"
features = ["extension-module"]

[dev-dependencies]
criterion = "0.3"
rand = "0.8.0"
itertools = "0.10.0"
itertools-num = "0.1.1"

[[bench]]
name = "my_benchmark"
harness = false
path = "src/my_benchmark.rs"
